image: docker:dind

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"


build_image:
  script:
#    - export DOCKER_HOST="tcp://localhost:2375"
    - docker build -t $CI_REGISTRY_IMAGE:latest -f deployment/Dockerfile .
    # push only for tags
#    - "[[ -z $CI_BUILD_TAG ]] && exit 0"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest


deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - kubectl get all --all-namespaces
#    - |
#    cat <<EOF | kubectl apply -f -
#        kind: Namespace
#        apiVersion: v1
#        metadata:
#          name: $KUBE_NAMESPACE
#        EOF
  environment:
    name: staging
    url: http://staging.dj.k8.example.com
  only:
  - master
