image: docker:stable

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
  - echo "Building the app"
  - docker build -t my-docker-image .
  - docker run my-docker-image /script/to/run/tests

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"


build_image:
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest -f deployment/Dockerfile .
    # push only for tags
#    - "[[ -z $CI_BUILD_TAG ]] && exit 0"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest


deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: http://staging.dj.k8.example.com
  only:
  - master
