apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-redis
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-redis
        version: {{ .Chart.Version }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          imagePullPolicy: Always
          image: redis
