apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgres-conntection-string: postgres://postgres:72jH9qVPA7@django-postgresql/postgres

